spring.application.name=tutor-platform

# Database
spring.datasource.url=jdbc:postgresql://localhost:5432/postgres
spring.datasource.username=postgres
spring.datasource.password=root
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update


# JPA
spring.jpa.properties.hibernate.default_schema=tutor
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.orm.jdbc.bind=TRACE
# JWT
app.jwt.secret=404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
app.jwt.expiration=86400000

# Server
server.port=8088

# CORS
app.cors.allowed-origins=http://localhost:4200

# Daily.co
daily.api.key=7ed9e3476b4b20f757769a5a218f6d943c0d8007ee878397a7cdad83a988350a
daily.api.base-url=https://api.daily.co/v1

# Email Api
mail.smtp.username=
mail.smtp.password=
mail.smtp.auth=true
mail.smtp.starttls.enable=true
mail.smtp.host=smtp.gmail.com
mail.smtp.port=587
